import { app, BrowserWindow, ipcMain } from 'electron';
import * as path from 'path';
import * as fs from 'fs/promises';
import { Prompt } from '../types';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const PROMPTS_DIR = path.join(app.getPath('userData'), 'prompts');
const SETTINGS_FILE = path.join(app.getPath('userData'), 'settings.json');

// Ensure the prompts directory exists
const ensurePromptsDir = async () => {
  try {
    await fs.access(PROMPTS_DIR);
  } catch {
    await fs.mkdir(PROMPTS_DIR, { recursive: true });
  }
};

// IPC Handlers
ipcMain.handle('get-app-version', () => app.getVersion());

ipcMain.handle('get-settings', async () => {
  try {
    const content = await fs.readFile(SETTINGS_FILE, 'utf-8');
    return JSON.parse(content);
  } catch (e) {
    return { disallowedDomains: '' };
  }
});

ipcMain.handle('save-settings', async (event, settings) => {
  await fs.writeFile(SETTINGS_FILE, JSON.stringify(settings, null, 2), 'utf-8');
  return true;
});

ipcMain.handle('get-prompts', async () => {
  await ensurePromptsDir();
  const files = await fs.readdir(PROMPTS_DIR);
  const jsonFiles = files.filter(f => f.endsWith('.json') && f !== 'order.json');
  
  const orderFilePath = path.join(PROMPTS_DIR, 'order.json');
  let order: string[] = [];
  try {
    const orderContent = await fs.readFile(orderFilePath, 'utf-8');
    order = JSON.parse(orderContent);
  } catch (e) {
    // order.json doesn't exist yet or is invalid
  }

  const prompts = await Promise.all(
    jsonFiles.map(async (file) => {
      const content = await fs.readFile(path.join(PROMPTS_DIR, file), 'utf-8');
      return JSON.parse(content) as Prompt;
    })
  );
  
  return prompts.sort((a, b) => {
    const indexA = order.indexOf(a.id);
    const indexB = order.indexOf(b.id);
    
    if (indexA !== -1 && indexB !== -1) {
      return indexA - indexB;
    }
    if (indexA !== -1) return -1;
    if (indexB !== -1) return 1;
    
    return b.createdAt - a.createdAt;
  });
});

ipcMain.handle('save-prompts-order', async (event, ids: string[]) => {
  await ensurePromptsDir();
  const filePath = path.join(PROMPTS_DIR, 'order.json');
  await fs.writeFile(filePath, JSON.stringify(ids), 'utf-8');
  return true;
});

ipcMain.handle('get-prompt', async (event, id: string) => {
  await ensurePromptsDir();
  const filePath = path.join(PROMPTS_DIR, `${id}.json`);
  const content = await fs.readFile(filePath, 'utf-8');
  return JSON.parse(content) as Prompt;
});

ipcMain.handle('create-prompt', async (event, prompt: Prompt) => {
  await ensurePromptsDir();
  const filePath = path.join(PROMPTS_DIR, `${prompt.id}.json`);
  await fs.writeFile(filePath, JSON.stringify(prompt, null, 2), 'utf-8');
  return true;
});

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 768,
    width: 1366,
    icon: path.join(__dirname, `../../assets/icon.${process.platform === 'win32' ? 'ico' : 'icns'}`),
    titleBarStyle: 'hidden',
    titleBarOverlay: process.platform === 'win32' ? {
      color: '#212529',
      symbolColor: '#ffffff',
      height: 44
    } : false,
    trafficLightPosition: { x: 15, y: 15 }, // Adjusted for 44px height
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
